config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[create index new show] do
      resources :comments, only: %i[create new]
      resources :likes, only: %i[create]
  end
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comments_count

  private

  def update_comments_count
    post.increment!(:comments_count)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper

  def create
    @comment = Comment.new(params.require(:comment).permit(:author_id, :post_id, :text))

    author_id = @comment.author_id
    post_id = @comment.post.id

    if @comment.save
      flash[:notice] = 'Comment has been saved successfully'
      redirect_to user_post_path(author_id, post_id)

    else
      flash[:error] = 'Comment could not be saved'
      redirect_to new_user_post_comment_path(author_id, post_id)
    end
  end

  def new
    @comment = Comment.new(author_id: current_user.id, post_id: params[:post_id])
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <%= comment.author.name %>: <%= comment.text %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<% flash.each do |key, message| %>
  <div class="error-message"><%= message %></div>
<% end %>
<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <%= form.hidden_field :author_id %><br>
  <%= form.hidden_field :post_id %><br>
  <div>
    <%= form.label :text, "Comment" %><br>
    <%= form.text_area :text %>
  </div>
  <%= form.submit %>
<% end %> 