config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[create index new show] do
      resources :comments, only: %i[create new]
      resources :likes, only: %i[create]
  end
end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: 'post_id'
  has_many :comments, foreign_key: 'post_id'

  after_save :update_posts_count

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def all_comments
    comments.includes([:author]).order(created_at: :desc)
  end

  def most_recent_comments
    all_comments.limit(5).limit(5)
  end

  def fulltext(short: false)
    short ? "#{text[0..150]}..." : text
  end

  private

  def update_posts_count
    author.increment!(:posts_counter)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def create
    @post = Post.new(params.require(:post).permit(:author_id, :title, :text))

    if @post.save
      flash[:notice] = 'Post has been saved successfully'
      redirect_to user_path(@post.author_id)
    else
      flash[:error] = 'Post could not be saved'
      redirect_to new_user_post_path(@post.author_id)
    end
  end

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(id: :desc)
  rescue ActiveRecord::RecordNotFound
    redirect_to users_path
  end

  def new
    p current_user
    @post = Post.new(author_id: current_user.id)
  end

  def show
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to action: 'index'
  end
end

app/helpers/post_helper.rb
module PostHelper
  def with_comments?(post)
    post.comments_count.positive? && !current_page?(user_path(post.author_id))
  end

  def short_text?(post)
    !current_page?(user_post_path(post.author_id, post.id))
  end
end

app/views/posts/_comments.html.erb
<% if with_comments?(post) %>
  <div id="comment-list" class="column box">
    <% if short_text?(post) %>
      <%= render post.most_recent_comments %>
    <% else %>
      <%= render post.all_comments %>
    <% end %>
  </div>
<% end %>

app/views/posts/_count.html.erb
Comments: <%= post.comments_count %>, Likes: <%= post.likes_count %>

app/views/posts/_footer.html.erb
<% if short_text?(post) %>
  <div class="row-right">
    <h4><%= render 'posts/count', post: post %></h4>
  </div>
<% end %>
<div class="row-right">
  <%= button_to 'New comment', new_user_post_comment_path(post.author_id, post.id), method: :get %>
    &nbsp;
    <%= button_to 'Like', user_post_likes_path(post.author_id, post), method: :post %>
</div>

app/views/posts/_header.html.erb
<% if short_text?(post) %>
  <h3><%= link_to(user_post_path(post.author_id, post.id)) { post.title } %></h3>
<% else %>
  <div class="row-justify">
    <h3><%= post.title %> by <%= link_to(user_path(post.author_id)) { post.author.name } %> </h3>
    <h4><%= render 'posts/count', post: post %></h4>
  </div>
<% end %>

app/views/posts/_post.html.erb
# <div class="box-no-border">
<div class="postin">
  <div class="column box">
    <%= render 'posts/header', post: post %>
    <p><%= post.fulltext(short: short_text?(post)) %></p>
    <%= render 'posts/footer', post: post %>
  </div>
  <%= render 'posts/comments', post: post %>
</div>

app/views/posts/index.html.erb
<input type="hidden" value="<%= "here is a list of posts by user with id: #{@user.id}" %>"
# <div id="authors_part" class="author-div">
  <%= render @user %>
  <div id="post-list">
  <%= render @posts %>
  </div>
  <div class="row-center"><h3>Pagination</h3></div>
# </div> 

app/views/posts/new.html.erb
<h1>New Post</h1>

<% flash.each do |key, message| %>
  <div><%= message %></div>
<% end %>
<%= form_with model: @post, url: user_posts_path do |form| %>
  <%= form.hidden_field :author_id %><br>
  <div>
    <%= form.label :title, "Title" %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text, "Text" %><br>
    <%= form.text_area :text %>
  </div>
  <%= form.submit %>
<% end %>  

app/views/posts/show.html.erb
<input type="hidden" value="<%= "show exact post with id: #{@post.id} by User with id: #{@post.author_id}" %>" />
# <div id="authors_part" class="author-div">
<div class="box-no-border">
  <%= render @post %>
</div>